spring:
  application:
    name: Guessimate API
  threads:
    virtual:
      enabled: true
  datasource:
    name: guessimate
    url: jdbc:postgresql://postgres:5432/guessimate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: guessimate-pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      validation-timeout: 5000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  jpa:
    open-in-view: false

otel:
  trace:
    endpoint: http://tempo:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always